apiVersion: v2
name: piggy-webhooks
description: Deploys a piggy-webhooks that inject enviroment variaiables from AWS Secret Manager
type: application
version: 0.6.2
appVersion: "0.6.2"
home: https://piggysec.com
icon: https://raw.githubusercontent.com/KongZ/piggy/refs/heads/main/docs/images/gopher-piggy.png
sources:
  - https://www.github.com/KongZ/piggy
maintainers:
  - name: KongZ
    email: goonohc@gmail.com
keywords:
  - aws
  - eks
  - secret manager