apiVersion: v2
name: piggy-webhooks
description: Deploys a piggy-webhooks that inject environment variables from AWS Secrets Manager
type: application
version: 0.7.3
appVersion: "0.7.3"
home: https://piggysec.com
icon: https://raw.githubusercontent.com/KongZ/piggy/refs/heads/main/docs/images/gopher-piggy.png
sources:
  - https://www.github.com/KongZ/piggy
maintainers:
  - name: KongZ
    email: goonohc@gmail.com
keywords:
  - aws
  - eks
  - secrets manager
